### ISSUE TITLE
feat: new queries generation

### ISSUE THREAD

**Issue by yyyyaaa** [pyramation/graphile-gen#17]
Graphilegen:

```
- query for no sub fields (1)
- query for everything sub fields (2) 
- query for white-list of sub fields (3)
- query for no sub fields with count (4)
```

```
- many-many: autocomplete use (1)
- spreadsheet rows use (4)
- single cell selection use (3)
```

**Comment by pyramation** [comment]
I started to prototype some concepts we can use as a reference or even use this branch: https://github.com/pyramation/graphile-gen/pull/18

**Comment by pyramation** [comment]
The interface I'm imagining is something like

```js
 const gen = generate({ ...queries, ...mutations }, 'Action', [
    'id',
    'name',
    'approved'
  ]);
```

**Comment by pyramation** [comment]
@yyyyaaa you'll notice, it still names the hash keys the same as the original: https://github.com/pyramation/graphile-gen/pull/18/files#diff-f8821e903506eaaedb1b1a0264ae7b6fe295c1a4300aa50c6f67f885531885aaR13

I suppose that's what we want? Or would we want to name these generic names? Since we can ask it to limit to only one model, in the example above, `Action`... then we're not getting back the giant full schema, only the stuff relevant for that object. So we could return more generic named hash keys if that makes sense:

```
 "getActionsPaginated": "query getActionsPaginated($first: Int, $last: Int, $offset: Int, $after: Cursor, $before: Cursor, $condition: ActionCondition, $filter: ActionFilter, $orderBy: [ActionsOrderBy!]) {
  actions(first: $first, last: $last, offset: $offset, after: $after, before: $before, condition: $condition, filter: $filter, orderBy: $orderBy) {totalCount, pageInfo {
    hasNextPage
    hasPreviousPage
    endCursor
    startCursor
  }, edges {
    cursor
    node {
      id
      name
      approved
    }
  }}
```

Could be `getManyPaginated` (but I'm not sure we need to do this or if it helps in the context of where we're using this)

```
 "getManyPaginated": "query getActionsPaginated($first: Int, $last: Int, $offset: Int, $after: Cursor, $before: Cursor, $condition: ActionCondition, $filter: ActionFilter, $orderBy: [ActionsOrderBy!]) {
  actions(first: $first, last: $last, offset: $offset, after: $after, before: $before, condition: $condition, filter: $filter, orderBy: $orderBy) {totalCount, pageInfo {
    hasNextPage
    hasPreviousPage
    endCursor
    startCursor
  }, edges {
    cursor
    node {
      id
      name
      approved
    }
  }}
```

**Comment by pyramation** [comment]
@yyyyaaa I have to admit, your `getSelections` function made this all very easy! Good job with that one ;)

**Comment by pyramation** [comment]
### super basic pagination for subfields

Here is an idea for an interface if we want to expand it beyond `3`, and allow us to specify a number:

```js
  const gen = generate(
    { ...queries, ...mutations },
    'ActionItem',
    ['userActionItems'],
    {
      userActionItems: {
        first: 10,
        offset: 10
      }
    }
  );
```

**Comment by pyramation** [comment]
to implement granular counts, I made another separate branch to keep track of those ideas/changes: https://github.com/pyramation/graphile-gen/pull/19/files

I essentially added the pagination object that is the 4th argument to the `generateGranular` function

**Comment by pyramation** [comment]
@yyyyaaa I'm starting to think this would be implemented well with JS classes. Potentially we initiate the class by passing in the schema. Then various methods will return the specific model queries, with any additional parameters. Just a thought after editing this stuff, feels like it could help organize some things.

Maybe we do that later, since the class structure isn't completely clear yet, but if you have ideas, please let me know!

**Comment by pyramation** [comment]
@yyyyaaa something like this maybe? Just 🧠   brainstorming ;)

```js
const queryClient = new queryClient({ ...queries, ...mutations });

const userQuery = queryClient.getMany(
    'Users',
    ['userActionItems', 'emails'],
    {
        userActionItems: {
            first: 10,
            offset: 10
        },
        emails: {
            first: 1,
            offset: 0,
            include: [
                'id', 'email'
            ]
        }
    }
);

const users = await gqlClient.query(userQuery);

```

**Comment by pyramation** [comment]
some examples from prisma client:

```js
const result = await prisma.user.findMany({
  select: {
    id: true,
    name: true,
    posts: {
      include: {
        author: true,
      },
    },
  },
})
```

**Comment by yyyyaaa** [comment]
ohh, sorry I just woke up, reading the branches you created now :)

**Comment by pyramation** [comment]
cool! sorry for spamming this issue with comments, I guess I got excited after our conversation yesterday! Take it easy and enjoy the morning and have a good breakfast first! ;)

**Comment by yyyyaaa** [comment]
ohh I really like the `select` and `include` params from prisma, this is the interface I thought of yesterday
Please tell me what you think cc @pyramation 
```
import { IntrospectionQuery, parseGraphQuery } from 'introspectron';

// Get meta schema and introspection first on client side
const _meta = fetch(MetaQuery);
const introspection = fetch(IntrospectionQuery);
const { queries, mutations } = parseGraphQuery(introspection);

// Then pass into the client
const client = new GraphileGenClient({
  _meta,
  queries,
  mutations
});

// Return all queries and mutations of all models
// Default will query all scalar fields, no relation fields
const all = client.query({
  eager: true,
  // If eager=true, eagerCount imposes the max amount of nodes
  maxEagerPerField: 3,
});

// Return "getActionsQuery" of model "Action"
// returns { "getActionsQueryAll": '...', ... }
const getActionsMany = client.query('Action').getMany({
  select: {
    "id": true,
    "name": true,
    "photo": true,
    "title": true,
    "actionResults": {
      select: {
        id: true
      },
      variables: {
        first: 10,
        last: 10,
        before: null,
      }
    }
  }
});

const getAction = client.query('Action').getOne({
  select: {
    "id": true,
    "name": true,
    "photo": true,
    "title": true,
    "actionResults": {
      select: {
        id: true
      },
      variables: {
        first: 10,
        last: 10,
        before: null,
      }
    }
  }
});

```

**Comment by pyramation** [comment]
woah @yyyyaaa! that's amazing. It looks super intuitive! I think we can do something like this!!

I may ask, why is `_meta` required in this case? Out of curiousity?

**Comment by pyramation** [comment]
@yyyyaaa if we have a tool like this that is sort of ORM-like, or class-based, I think we'll be able to handle all of our dynamic query needs!

**Comment by pyramation** [comment]
we should probably leave graphile-gen alone and make this a new package in this repo. I did push to master `packages/graphile-client` if you want we can use that it was available on npm so I got it for us to use

**Comment by yyyyaaa** [comment]
> woah @yyyyaaa! that's amazing. It looks super intuitive! I think we can do something like this!!
> 
> I may ask, why is `_meta` required in this case? Out of curiousity?

Ah, it might not be necessary at all, at first I thought: How could graphile-gen know which field is relation, we can't simply rely on the condition that relation = object type, because for example `ownerId` is scalar, but it's relation. We don't know anything from only graphile-gen side.

**Comment by pyramation** [comment]
This will be way more flexible than our current system. I liked your API example. Do you want to make the class with your API described above? We can put it here if you think it makes sense to make this a clean package: https://github.com/pyramation/graphile-gen/tree/master/packages/graphile-client

**Comment by yyyyaaa** [comment]
Maybe there should be a common format for relation meta data, so I convert from `_meta` to that structure. Then feed it to graphile-gen

**Comment by yyyyaaa** [comment]
That way it's not super coupled to _meta

**Comment by pyramation** [comment]
also, we can move this repo out of pyramation over to one of our orgs soon

**Comment by pyramation** [comment]
> Maybe there should be a common format for relation meta data, so I convert from `_meta` to that structure. Then feed it to graphile-gen

Yea this makes sense. I think `_meta` needs some updates too

**Comment by pyramation** [comment]
> > woah @yyyyaaa! that's amazing. It looks super intuitive! I think we can do something like this!!
> > I may ask, why is `_meta` required in this case? Out of curiousity?
> 
> Ah, it might not be necessary at all, at first I thought: How could graphile-gen know which field is relation, we can't simply rely on the condition that relation = object type, because for example `ownerId` is scalar, but it's relation. We don't know anything from only graphile-gen side.

This is a super good point. We will have it when we're using the app, so I can see where we'd want to have this type of information

**Comment by pyramation** [comment]
> > woah @yyyyaaa! that's amazing. It looks super intuitive! I think we can do something like this!!
> > I may ask, why is `_meta` required in this case? Out of curiousity?
> 
> Ah, it might not be necessary at all, at first I thought: How could graphile-gen know which field is relation, we can't simply rely on the condition that relation = object type, because for example `ownerId` is scalar, but it's relation. We don't know anything from only graphile-gen side.

Maybe it's good to build the first version to be super flexible ORM-class like object, and then we use `_meta` to create the objects we pass into the instance methods of the class?

**Comment by yyyyaaa** [comment]
> also, we can move this repo out of pyramation over to one of our orgs soon


Yes, let me think of a sensible format.
It could be just JSON for simplicity

**Comment by pyramation** [comment]
> Maybe there should be a common format for relation meta data, so I convert from `_meta` to that structure. Then feed it to graphile-gen

I read this again and realized this is exactly what you said! I think we're on the exact same page 😎

**Comment by pyramation** [comment]
I like your idea of making it OG JavaScript style classes where the instance methods always return `this` for chaining. 

This will make it super composable.

**Comment by pyramation** [comment]
I started to tinker a bit for some ideas:

https://github.com/pyramation/graphile-gen/blob/d52139f8d62aa0a76d714135d53c6a31d20caaa9/packages/graphile-client/__tests__/client.test.js

https://github.com/pyramation/graphile-gen/blob/d52139f8d62aa0a76d714135d53c6a31d20caaa9/packages/graphile-client/__tests__/__snapshots__/client.test.js.snap

**Comment by pyramation** [comment]
@yyyyaaa if you want we can use this branch and evolve this: https://github.com/pyramation/graphile-gen/pull/21

I have the testing setup, and also copied the `gql.js` over so we can clean it up without breaking graphile-gen as we evolve the client

**Comment by pyramation** [comment]
I'll let you check it out and see your thoughts

**Comment by yyyyaaa** [comment]
@pyramation oops, sorry I didn't reply on time! I'm also prototyping! gonna create a PR soon! I will rebase off of your `feat/client` branch

**Comment by pyramation** [comment]
ok cool! sounds good! I'll stop tinkering around now so you can take it over from here! I just wanted to clean up the AST generation and put it in the client branch. 

I'm pretty stoked for this 🚀

**Comment by pyramation** [comment]
just in case you want to you can checkout the tests in `feat/client`, and cd `packages/graphile-client` and then 

```
yarn test:watch
```

it's nice to to TDD here ;)

**Comment by yyyyaaa** [comment]
@pyramation gotcha! been TDD in graphile-gen since I first touched it :) don't worry, I even wrote a JSON schema format for the meta data format for validating with ajv

**Comment by pyramation** [comment]
you are the man! thanks @yyyyaaa 

I love that you used ajv 🙌🏻

**Comment by pyramation** [comment]
closing this as we merged your amazing work! thanks again :)
